name: "Build Windows"

inputs:
  channel:
    required: true

runs:
  using: "composite"
  steps:
    - name: 📦 Build the Windows artifact
      shell: bash
      run: CHANNEL=${{ inputs.channel }} ./build.sh dist-windows

    - name: 🔨 Create Windows installer
      uses: joncloud/makensis-action@v4.1
      with:
        script-file: "Installer.nsi"

    - name: ✍️ Sign the Windows installer
      shell: cmd
      run: C:\signing\sign.bat dist\Casterlabs-Caffeinated-Setup.exe

    - name: 🆙 Upload the Windows artifact (x86_64)
      uses: actions/upload-artifact@v4
      with:
        name: Casterlabs-Caffeinated-windows-x86_64-${{ inputs.channel }}.zip
        path: dist/artifacts/Casterlabs-Caffeinated-Updater-windows-x86_64.zip

    - name: 🆙 Upload the Windows installer (x86_64)
      uses: actions/upload-artifact@v4
      with:
        name: Casterlabs-Caffeinated-Setup-${{ inputs.channel }}.exe
        path: dist/Casterlabs-Caffeinated-Setup.exe
